//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sieve.API.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sieve.API.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [
        ///  {
        ///    &quot;RegionId&quot;: 1,
        ///    &quot;CountryId&quot;: 1,
        ///    &quot;Id&quot;: 1,
        ///    &quot;Name&quot;: &quot;Arghanj Khwah&quot;
        ///  },
        ///  {
        ///    &quot;RegionId&quot;: 1,
        ///    &quot;CountryId&quot;: 1,
        ///    &quot;Id&quot;: 2,
        ///    &quot;Name&quot;: &quot;Argo&quot;
        ///  },
        ///  {
        ///    &quot;RegionId&quot;: 1,
        ///    &quot;CountryId&quot;: 1,
        ///    &quot;Id&quot;: 3,
        ///    &quot;Name&quot;: &quot;Baharak&quot;
        ///  },
        ///  {
        ///    &quot;RegionId&quot;: 1,
        ///    &quot;CountryId&quot;: 1,
        ///    &quot;Id&quot;: 4,
        ///    &quot;Name&quot;: &quot;Darayim&quot;
        ///  },
        ///  {
        ///    &quot;RegionId&quot;: 1,
        ///    &quot;CountryId&quot;: 1,
        ///    &quot;Id&quot;: 5,
        ///    &quot;Name&quot;: &quot;Darwaz-e Bala&quot;
        ///  },
        ///  {
        ///    &quot;RegionId&quot;: 1,
        ///    &quot;CountryId&quot;: 1,
        ///    &quot;Id&quot;: [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [
        ///  {
        ///    &quot;Code&quot;: &quot;AF&quot;,
        ///    &quot;Id&quot;: 1,
        ///    &quot;Name&quot;: &quot;Afghanistan&quot;
        ///  },
        ///  {
        ///    &quot;Code&quot;: &quot;AL&quot;,
        ///    &quot;Id&quot;: 2,
        ///    &quot;Name&quot;: &quot;Albania&quot;
        ///  },
        ///  {
        ///    &quot;Code&quot;: &quot;DZ&quot;,
        ///    &quot;Id&quot;: 3,
        ///    &quot;Name&quot;: &quot;Algeria&quot;
        ///  },
        ///  {
        ///    &quot;Code&quot;: &quot;AD&quot;,
        ///    &quot;Id&quot;: 4,
        ///    &quot;Name&quot;: &quot;Andorra&quot;
        ///  },
        ///  {
        ///    &quot;Code&quot;: &quot;AO&quot;,
        ///    &quot;Id&quot;: 5,
        ///    &quot;Name&quot;: &quot;Angola&quot;
        ///  },
        ///  {
        ///    &quot;Code&quot;: &quot;AI&quot;,
        ///    &quot;Id&quot;: 6,
        ///    &quot;Name&quot;: &quot;Anguilla&quot;
        ///  },
        ///  {
        ///    &quot;Code&quot;: &quot;AG&quot;,
        ///    &quot;Id&quot;: 7,
        ///    &quot;Name&quot;: &quot;Antigua and Barbuda&quot;
        ///  },
        ///  {
        ///    &quot;Code&quot;: &quot;AR&quot;,
        /// [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [
        ///  {
        ///    &quot;CountryId&quot;: 1,
        ///    &quot;Id&quot;: 1,
        ///    &quot;Name&quot;: &quot;Badakhshan&quot;
        ///  },
        ///  {
        ///    &quot;CountryId&quot;: 1,
        ///    &quot;Id&quot;: 2,
        ///    &quot;Name&quot;: &quot;Badghis&quot;
        ///  },
        ///  {
        ///    &quot;CountryId&quot;: 1,
        ///    &quot;Id&quot;: 3,
        ///    &quot;Name&quot;: &quot;Balkh&quot;
        ///  },
        ///  {
        ///    &quot;CountryId&quot;: 1,
        ///    &quot;Id&quot;: 4,
        ///    &quot;Name&quot;: &quot;Daykundi Province&quot;
        ///  },
        ///  {
        ///    &quot;CountryId&quot;: 1,
        ///    &quot;Id&quot;: 5,
        ///    &quot;Name&quot;: &quot;Farah&quot;
        ///  },
        ///  {
        ///    &quot;CountryId&quot;: 1,
        ///    &quot;Id&quot;: 6,
        ///    &quot;Name&quot;: &quot;Faryab Province&quot;
        ///  },
        ///  {
        ///    &quot;CountryId&quot;: 1,
        ///    &quot;Id&quot;: 7,
        ///    &quot;Name&quot;: &quot;Helmand&quot;
        ///  },
        ///  {
        ///     [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
    }
}
